from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_NewPatient(object):
    def setupUi(self, NewPatient):
        NewPatient.setObjectName("NewPatient")
        NewPatient.resize(794, 498)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 242, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 242, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 242, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 242, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        NewPatient.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(NewPatient)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_first_name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_first_name.setFont(font)
        self.label_first_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_first_name.setObjectName("label_first_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_first_name)
        self.textbox_first_name = QtWidgets.QLineEdit(self.centralwidget)
        self.textbox_first_name.setObjectName("textbox_first_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textbox_first_name)
        self.label_last_name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_last_name.setFont(font)
        self.label_last_name.setObjectName("label_last_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_last_name)
        self.textbox_last_name = QtWidgets.QLineEdit(self.centralwidget)
        self.textbox_last_name.setObjectName("textbox_last_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textbox_last_name)
        self.label_dob = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_dob.setFont(font)
        self.label_dob.setObjectName("label_dob")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_dob)
        self.date_edit = QtWidgets.QDateEdit(self.centralwidget)
        self.date_edit.setObjectName("date_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.date_edit)
        self.label_mrn = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_mrn.setFont(font)
        self.label_mrn.setObjectName("label_mrn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_mrn)
        self.textbox_mrn = QtWidgets.QLineEdit(self.centralwidget)
        self.textbox_mrn.setObjectName("textbox_mrn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textbox_mrn)
        self.label_indication = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_indication.setFont(font)
        self.label_indication.setObjectName("label_indication")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_indication)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.radioButton_yes = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_yes.setObjectName("radioButton_yes")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.radioButton_yes)
        self.radioButton_no = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_no.setObjectName("radioButton_no")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.radioButton_no)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.verticalLayout.addWidget(self.buttonBox_2)
        NewPatient.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(NewPatient)
        self.statusbar.setObjectName("statusbar")
        NewPatient.setStatusBar(self.statusbar)

        self.retranslateUi(NewPatient)
        QtCore.QMetaObject.connectSlotsByName(NewPatient)

    def retranslateUi(self, NewPatient):
        _translate = QtCore.QCoreApplication.translate
        NewPatient.setWindowTitle(_translate("NewPatient", "MainWindow"))
        self.label.setText(_translate("NewPatient", "New Patient Form"))
        self.label_first_name.setText(_translate("NewPatient", "First Name"))
        self.label_last_name.setText(_translate("NewPatient", "Last Name"))
        self.label_dob.setText(_translate("NewPatient", "Date of Birth"))
        self.label_mrn.setText(_translate("NewPatient", "Medical Record Number"))
        self.label_indication.setText(_translate("NewPatient", "Indication"))
        self.comboBox.setItemText(0, _translate("NewPatient", "Atrial Fibrillation"))
        self.comboBox.setItemText(1, _translate("NewPatient", "Atrial Flutter"))
        self.comboBox.setItemText(2, _translate("NewPatient", "Acute VTE"))
        self.comboBox.setItemText(3, _translate("NewPatient", "Prophylaxis"))
        self.comboBox.setItemText(4, _translate("NewPatient", "Mitral Valve Replacement"))
        self.comboBox.setItemText(5, _translate("NewPatient", "Recurrent VTE"))
        self.comboBox.setItemText(6, _translate("NewPatient", "Other"))
        self.radioButton_yes.setText(_translate("NewPatient", "Yes"))
        self.radioButton_no.setText(_translate("NewPatient", "No"))
        self.label_2.setText(_translate("NewPatient", "Is the patient a new start?"))


if __name__ == "__main__":
    myapp = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QMainWindow()
    main_ui = Ui_NewPatient()
    main_ui.setupUi(main)
    main.show()
    sys.exit(myapp.exec_())