# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_update_event.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgAddEditEvent(object):
    def setupUi(self, DlgAddEditEvent):
        DlgAddEditEvent.setObjectName("DlgAddEditEvent")
        DlgAddEditEvent.resize(622, 621)
        DlgAddEditEvent.setStyleSheet(
            """
        QDialog {
                background-color: #f5f5f5;}
        
        QLabel {
                font-family: \"Source Sans Pro\";
                font-size: 16px;
                font-weight: bold;
                color: #696969;}
            
        QListWidget{
            border: 1px solid #00b4d8; 
            border-radius:10px; 
            background-color: palette(base);
            padding: 5px;
        }           
        
        QListWidget::item::hover{
            background-color: #b3e9f3;}
        
        QListWidget::item::selected{
            color: #004856;
            background-color: #b3e9f3;}

        QPushButton {
                background-color: #00b4d8;
                color: white;
                border-radius: 8px;
                font-family: \"Raleway\";
                font-size: 12px;
                border: none;}
                
        QPushButton::hover {
                background-color: #b3e9f3;}
                
        QLineEdit {
                border-left: 2px solid #00b4d8;
                border-right: 2px solid #00b4d8;
                padding: 10px;
                font-family:  \"Raleway\";
                font: 12px;
                border-radius: 10px;}   
                
        QTextEdit{
            border: 2px dashed #00b4d8; 
            border-radius:10px; 
            background-color: palette(base);
            padding: 15px;
        }           
            """

        )
        self.layoutWidget = QtWidgets.QWidget(DlgAddEditEvent)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 11, 601, 596))
        self.layoutWidget.setObjectName("layoutWidget")
        self.lytMain = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.lytMain.setContentsMargins(0, 0, 0, 0)
        self.lytMain.setObjectName("lytMain")
        self.lytDate = QtWidgets.QHBoxLayout()
        self.lytDate.setObjectName("lytDate")
        self.lblDate_event = QtWidgets.QLabel(self.layoutWidget)
        self.lblDate_event.setObjectName("lblDate_event")
        self.lytDate.addWidget(self.lblDate_event)
        self.dteDate_event = QtWidgets.QDateEdit(self.layoutWidget)
        self.dteDate_event.setCalendarPopup(True)
        self.dteDate_event.setObjectName("dteDate_event")
        self.lytDate.addWidget(self.dteDate_event)
        spacerItem = QtWidgets.QSpacerItem(800, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.lytDate.addItem(spacerItem)
        self.lytMain.addLayout(self.lytDate)
        self.labelEvent = QtWidgets.QLabel(self.layoutWidget)
        self.labelEvent.setObjectName("labelEvent")
        self.lytMain.addWidget(self.labelEvent)
        self.lytBottom = QtWidgets.QHBoxLayout()
        self.lytBottom.setObjectName("lytBottom")
        self.lytLeft = QtWidgets.QVBoxLayout()
        self.lytLeft.setObjectName("lytLeft")
        self.lytAddEvent = QtWidgets.QHBoxLayout()
        self.lytAddEvent.setObjectName("lytAddEvent")
        self.ledNewEvent = QtWidgets.QLineEdit(self.layoutWidget)
        self.ledNewEvent.setObjectName("ledNewEvent")
        self.lytAddEvent.addWidget(self.ledNewEvent)
        self.btnAddToEventList = QtWidgets.QPushButton(self.layoutWidget)
        self.btnAddToEventList.setMinimumSize(QtCore.QSize(60, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icon/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddToEventList.setIcon(icon)
        self.btnAddToEventList.setObjectName("btnAddToEventList")
        self.lytAddEvent.addWidget(self.btnAddToEventList)
        self.lytLeft.addLayout(self.lytAddEvent)
        self.lstCurrentEvent = QtWidgets.QListWidget(self.layoutWidget)
        self.lstCurrentEvent.setObjectName("lstCurrentEvent")
        self.lytLeft.addWidget(self.lstCurrentEvent)
        self.lytBottom.addLayout(self.lytLeft)
        self.lytEventButtons = QtWidgets.QVBoxLayout()
        self.lytEventButtons.setObjectName("lytEventButtons")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.lytEventButtons.addItem(spacerItem1)
        self.btnAddToPatient = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddToPatient.sizePolicy().hasHeightForWidth())
        self.btnAddToPatient.setSizePolicy(sizePolicy)
        self.btnAddToPatient.setMinimumSize(QtCore.QSize(40, 20))
        self.btnAddToPatient.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/icon/add_to.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddToPatient.setIcon(icon1)
        self.btnAddToPatient.setIconSize(QtCore.QSize(24, 24))
        self.btnAddToPatient.setObjectName("btnAddToPatient")
        self.lytEventButtons.addWidget(self.btnAddToPatient)
        self.btnRemoveFromPatient = QtWidgets.QPushButton(self.layoutWidget)
        self.btnRemoveFromPatient.setMinimumSize(QtCore.QSize(0, 20))
        self.btnRemoveFromPatient.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/icon/remove_from.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemoveFromPatient.setIcon(icon2)
        self.btnRemoveFromPatient.setIconSize(QtCore.QSize(24, 24))
        self.btnRemoveFromPatient.setObjectName("btnRemoveFromPatient")
        self.lytEventButtons.addWidget(self.btnRemoveFromPatient)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.lytEventButtons.addItem(spacerItem2)
        self.lytBottom.addLayout(self.lytEventButtons)
        self.lstPatientEvent = QtWidgets.QListWidget(self.layoutWidget)
        self.lstPatientEvent.setObjectName("lstPatientEvent")
        self.lytBottom.addWidget(self.lstPatientEvent)
        self.lytMain.addLayout(self.lytBottom)
        self.lblComment = QtWidgets.QLabel(self.layoutWidget)
        self.lblComment.setObjectName("lblComment")
        self.lytMain.addWidget(self.lblComment)
        self.txtComment_event = QtWidgets.QTextEdit(self.layoutWidget)
        self.txtComment_event.setTabChangesFocus(False)
        self.txtComment_event.setObjectName("txtComment_event")
        self.lytMain.addWidget(self.txtComment_event)
        self.lytButton = QtWidgets.QHBoxLayout()
        self.lytButton.setObjectName("lytButton")
        self.btnOK = QtWidgets.QPushButton(self.layoutWidget)
        self.btnOK.setMinimumSize(QtCore.QSize(0, 25))
        self.btnOK.setObjectName("btnOK")
        self.lytButton.addWidget(self.btnOK)
        self.btnCancelDialog = QtWidgets.QPushButton(self.layoutWidget)
        self.btnCancelDialog.setMinimumSize(QtCore.QSize(0, 25))
        self.btnCancelDialog.setObjectName("btnCancelDialog")
        self.lytButton.addWidget(self.btnCancelDialog)
        self.lytMain.addLayout(self.lytButton)

        self.retranslateUi(DlgAddEditEvent)
        QtCore.QMetaObject.connectSlotsByName(DlgAddEditEvent)

    def retranslateUi(self, DlgAddEditEvent):
        _translate = QtCore.QCoreApplication.translate
        DlgAddEditEvent.setWindowTitle(_translate("DlgAddEditEvent", "Add Event"))
        self.lblDate_event.setText(_translate("DlgAddEditEvent", "Date"))
        self.labelEvent.setText(_translate("DlgAddEditEvent", "Clinical Event"))
        self.ledNewEvent.setPlaceholderText(_translate("DlgAddEditEvent", "Type new clinical event here"))
        self.btnAddToEventList.setToolTip(_translate("DlgAddEditEvent", "Add new indication to list of indications in the database"))
        self.btnAddToEventList.setText(_translate("DlgAddEditEvent", "Add"))
        self.btnAddToPatient.setToolTip(_translate("DlgAddEditEvent", "Add indication to patient\'s profile"))
        self.btnRemoveFromPatient.setToolTip(_translate("DlgAddEditEvent", "Remove indication from patient\'s profile"))
        self.lblComment.setText(_translate("DlgAddEditEvent", "Comment"))
        self.txtComment_event.setToolTip(_translate("DlgAddEditEvent", "Add clinically relevant comments"))
        self.txtComment_event.setPlaceholderText(_translate("DlgAddEditEvent", "Type any clinically relevant information pertaining to the result."))
        self.btnOK.setText(_translate("DlgAddEditEvent", "OK"))
        self.btnCancelDialog.setText(_translate("DlgAddEditEvent", "Cancel"))
import resource.resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgAddEditEvent = QtWidgets.QDialog()
    ui = Ui_DlgAddEditEvent()
    ui.setupUi(DlgAddEditEvent)
    DlgAddEditEvent.show()
    sys.exit(app.exec_())
