# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patientlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgPatients(object):
    def setupUi(self, DlgPatients):
        DlgPatients.setObjectName("DlgPatients")
        DlgPatients.resize(404, 584)
        DlgPatients.setStyleSheet(
            """
            QDialog {
                background-color: #f5f5f5;}
                
            QLabel#lblHeader {
                color: #5E60CE;
                font-family: \"Source Sans Pro\";
                font-size: 24px;}
                
            QPushButton {
                background-color: #00b4d8;
                color: white;
                border-radius: 8px;
                font-family: \"Raleway\";
                font-size: 12px;
                border: none;}
                
            QPushButton::hover {
                background-color: #b3e9f3;}  
                
            QTableWidget{
                width: 24px;
                height: 24px;
                border-radius: 4px;}  
                
            QLineEdit {
                border: none;
                background-color: transparent;}
                
            QTableCornerButton::section {
                background-color: #f5f5f5;
                border-radius: 0px;
                border-right: 1px solid;
                border-bottom: 1px solid;
                border-color: #e6e6e6;}
                
            QHeaderView {
                border: none;}
                
            QTableView {
                alternate-background-color: {{#f5f5f5|opacity(0.7)}};}
            
            QHeaderView::section {
                color: {{#555555|opacity(0.7)}};
                text-transform: uppercase;
                background-color: #f5f5f5;
                padding: 0 20px;
                height: 35px;
                border-radius: 0px;
                border-right: 1px solid;
                border-bottom: 1px solid;
                border-color: #e6e6e6;}    
    
            QRadioButton{
                spacing: 10px;
                color: #555555;
                line-height: 14px;
                height: 30px;
                background-color: transparent;
                spacing: 5px;}

            QRadioButton:disabled{
              color: {{#555555|opacity(0.3)}};}

            QRadioButton::indicator {
                background-color: transparent;
                width: 24px;
                height: 24px;
                border-radius: 4px;}
 
            QRadioButton::indicator:checked {
                image: url(../resource/icon/radio button checked.svg);}

            QRadioButton::indicator:unchecked {
                image: url(..resource/icon/radio button unchecked.svg);}

            QRadioButton::indicator:checked:disabled {
                image: url(../resource/icon/radio button checked.svg);}
            
            QRadioButton::indicator:unchecked:disabled {
                image: url(..resource/icon/radio button unchecked.svg);} 
            """
        )
        self.layoutWidget = QtWidgets.QWidget(DlgPatients)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 561))
        self.layoutWidget.setObjectName("layoutWidget")
        self.lytMain = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.lytMain.setContentsMargins(0, 0, 0, 0)
        self.lytMain.setObjectName("lytMain")
        self.lblHeader = QtWidgets.QLabel(self.layoutWidget)
        self.lblHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeader.setObjectName("lblHeader")
        self.lytMain.addWidget(self.lblHeader)
        self.lytRadioButton = QtWidgets.QHBoxLayout()
        self.lytRadioButton.setObjectName("lytRadioButton")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lytRadioButton.addItem(spacerItem)
        self.rbtAll = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtAll.setStyleSheet("")
        self.rbtAll.setChecked(True)
        self.rbtAll.setObjectName("rbtAll")
        self.buttonGroup = QtWidgets.QButtonGroup(DlgPatients)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rbtAll)
        self.lytRadioButton.addWidget(self.rbtAll)
        self.rbtActive = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtActive.setStyleSheet("")
        self.rbtActive.setObjectName("rbtActive")
        self.buttonGroup.addButton(self.rbtActive)
        self.lytRadioButton.addWidget(self.rbtActive)
        self.rbtInactive = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtInactive.setStyleSheet("")
        self.rbtInactive.setObjectName("rbtInactive")
        self.buttonGroup.addButton(self.rbtInactive)
        self.lytRadioButton.addWidget(self.rbtInactive)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lytRadioButton.addItem(spacerItem1)
        self.lytMain.addLayout(self.lytRadioButton)
        self.lytTotal = QtWidgets.QHBoxLayout()
        self.lytTotal.setObjectName("lytTotal")
        self.lblTotal = QtWidgets.QLabel(self.layoutWidget)
        self.lblTotal.setObjectName("lblTotal")
        self.lytTotal.addWidget(self.lblTotal)
        self.ledTotal = QtWidgets.QLineEdit(self.layoutWidget)
        self.ledTotal.setReadOnly(True)
        self.ledTotal.setObjectName("ledTotal")
        self.lytTotal.addWidget(self.ledTotal)
        self.lytMain.addLayout(self.lytTotal)
        self.tblPatientList = QtWidgets.QTableWidget(self.layoutWidget)
        self.tblPatientList.setObjectName("tblPatientList")
        self.tblPatientList.setColumnCount(3)
        self.tblPatientList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 255))
        self.tblPatientList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblPatientList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblPatientList.setHorizontalHeaderItem(2, item)
        self.lytMain.addWidget(self.tblPatientList)
        self.lytExit = QtWidgets.QHBoxLayout()
        self.lytExit.setObjectName("lytExit")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lytExit.addItem(spacerItem2)
        self.btnExit = QtWidgets.QPushButton(self.layoutWidget)
        self.btnExit.setMinimumSize(QtCore.QSize(60, 30))
        self.btnExit.setObjectName("btnExit")
        self.lytExit.addWidget(self.btnExit)
        self.lytMain.addLayout(self.lytExit)

        self.retranslateUi(DlgPatients)
        QtCore.QMetaObject.connectSlotsByName(DlgPatients)

    def retranslateUi(self, DlgPatients):
        _translate = QtCore.QCoreApplication.translate
        DlgPatients.setWindowTitle(_translate("DlgPatients", "Patient List"))
        self.lblHeader.setText(_translate("DlgPatients", "Patient List"))
        self.rbtAll.setText(_translate("DlgPatients", "All"))
        self.rbtActive.setText(_translate("DlgPatients", "Active"))
        self.rbtInactive.setText(_translate("DlgPatients", "Inactive"))
        self.lblTotal.setText(_translate("DlgPatients", "Total:"))
        item = self.tblPatientList.horizontalHeaderItem(0)
        item.setText(_translate("DlgPatients", "MRN"))
        item = self.tblPatientList.horizontalHeaderItem(1)
        item.setText(_translate("DlgPatients", "Last Name"))
        item = self.tblPatientList.horizontalHeaderItem(2)
        item.setText(_translate("DlgPatients", "First Name"))
        self.btnExit.setText(_translate("DlgPatients", "Exit"))
import resource.resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgPatients = QtWidgets.QDialog()
    ui = Ui_DlgPatients()
    ui.setupUi(DlgPatients)
    DlgPatients.show()
    sys.exit(app.exec_())
