# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_update_event.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgAddEditEvent(object):
    def setupUi(self, DlgAddEditEvent):
        DlgAddEditEvent.setObjectName("DlgAddEditEvent")
        DlgAddEditEvent.resize(614, 618)
        DlgAddEditEvent.setStyleSheet("QDialog {\n"
"    background-color: #e2f2ff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #00b4d8;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    font-family: \"Readex Pro\";\n"
"    font: 12px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border: 3px solid #0077b6;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px  solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-family:  \"Readex Pro\";\n"
"    font: 12px;\n"
"\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #5E60CE;\n"
"    font-family: \"Raleway\";\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.widget = QtWidgets.QWidget(DlgAddEditEvent)
        self.widget.setGeometry(QtCore.QRect(10, 11, 591, 596))
        self.widget.setObjectName("widget")
        self.lytMain = QtWidgets.QVBoxLayout(self.widget)
        self.lytMain.setContentsMargins(0, 0, 0, 0)
        self.lytMain.setObjectName("lytMain")
        self.lytDate = QtWidgets.QHBoxLayout()
        self.lytDate.setObjectName("lytDate")
        self.lblDate_event = QtWidgets.QLabel(self.widget)
        self.lblDate_event.setObjectName("lblDate_event")
        self.lytDate.addWidget(self.lblDate_event)
        self.dteDate_event = QtWidgets.QDateEdit(self.widget)
        self.dteDate_event.setObjectName("dteDate_event")
        self.lytDate.addWidget(self.dteDate_event)
        spacerItem = QtWidgets.QSpacerItem(800, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.lytDate.addItem(spacerItem)
        self.lytMain.addLayout(self.lytDate)
        self.labelEvent = QtWidgets.QLabel(self.widget)
        self.labelEvent.setObjectName("labelEvent")
        self.lytMain.addWidget(self.labelEvent)
        self.lytBottom = QtWidgets.QHBoxLayout()
        self.lytBottom.setObjectName("lytBottom")
        self.lytLeft = QtWidgets.QVBoxLayout()
        self.lytLeft.setObjectName("lytLeft")
        self.lytAddEvent = QtWidgets.QHBoxLayout()
        self.lytAddEvent.setObjectName("lytAddEvent")
        self.ledNewEvent = QtWidgets.QLineEdit(self.widget)
        self.ledNewEvent.setObjectName("ledNewEvent")
        self.lytAddEvent.addWidget(self.ledNewEvent)
        self.btnNewEvent = QtWidgets.QPushButton(self.widget)
        self.btnNewEvent.setMinimumSize(QtCore.QSize(60, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNewEvent.setIcon(icon)
        self.btnNewEvent.setObjectName("btnNewEvent")
        self.lytAddEvent.addWidget(self.btnNewEvent)
        self.lytLeft.addLayout(self.lytAddEvent)
        self.lstCurrentEvent = QtWidgets.QListWidget(self.widget)
        self.lstCurrentEvent.setObjectName("lstCurrentEvent")
        self.lytLeft.addWidget(self.lstCurrentEvent)
        self.lytBottom.addLayout(self.lytLeft)
        self.lytEventButtons = QtWidgets.QVBoxLayout()
        self.lytEventButtons.setObjectName("lytEventButtons")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.lytEventButtons.addItem(spacerItem1)
        self.btnAddEvent = QtWidgets.QPushButton(self.widget)
        self.btnAddEvent.setMinimumSize(QtCore.QSize(40, 0))
        self.btnAddEvent.setObjectName("btnAddEvent")
        self.lytEventButtons.addWidget(self.btnAddEvent)
        self.btnRemoveEvent = QtWidgets.QPushButton(self.widget)
        self.btnRemoveEvent.setObjectName("btnRemoveEvent")
        self.lytEventButtons.addWidget(self.btnRemoveEvent)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.lytEventButtons.addItem(spacerItem2)
        self.lytBottom.addLayout(self.lytEventButtons)
        self.lstPatientEvent = QtWidgets.QListWidget(self.widget)
        self.lstPatientEvent.setObjectName("lstPatientEvent")
        self.lytBottom.addWidget(self.lstPatientEvent)
        self.lytMain.addLayout(self.lytBottom)
        self.lblComment = QtWidgets.QLabel(self.widget)
        self.lblComment.setObjectName("lblComment")
        self.lytMain.addWidget(self.lblComment)
        self.txtComment_event = QtWidgets.QTextEdit(self.widget)
        self.txtComment_event.setTabChangesFocus(False)
        self.txtComment_event.setObjectName("txtComment_event")
        self.lytMain.addWidget(self.txtComment_event)
        self.lytButton = QtWidgets.QHBoxLayout()
        self.lytButton.setObjectName("lytButton")
        self.btnOK_event = QtWidgets.QPushButton(self.widget)
        self.btnOK_event.setObjectName("btnOK_event")
        self.lytButton.addWidget(self.btnOK_event)
        self.btnCancel_event = QtWidgets.QPushButton(self.widget)
        self.btnCancel_event.setObjectName("btnCancel_event")
        self.lytButton.addWidget(self.btnCancel_event)
        self.lytMain.addLayout(self.lytButton)
        self.lblDate_event.raise_()
        self.dteDate_event.raise_()
        self.ledNewEvent.raise_()
        self.btnNewEvent.raise_()
        self.lstCurrentEvent.raise_()
        self.btnRemoveEvent.raise_()
        self.lstPatientEvent.raise_()
        self.btnAddEvent.raise_()
        self.txtComment_event.raise_()
        self.lblComment.raise_()

        self.retranslateUi(DlgAddEditEvent)
        QtCore.QMetaObject.connectSlotsByName(DlgAddEditEvent)

    def retranslateUi(self, DlgAddEditEvent):
        _translate = QtCore.QCoreApplication.translate
        DlgAddEditEvent.setWindowTitle(_translate("DlgAddEditEvent", "Add Event"))
        self.lblDate_event.setText(_translate("DlgAddEditEvent", "Date"))
        self.labelEvent.setText(_translate("DlgAddEditEvent", "Clinical Event"))
        self.ledNewEvent.setPlaceholderText(_translate("DlgAddEditEvent", "Type new clinical event here"))
        self.btnNewEvent.setToolTip(_translate("DlgAddEditEvent", "Add new indication to list of indications in the database"))
        self.btnNewEvent.setText(_translate("DlgAddEditEvent", "Add"))
        self.btnAddEvent.setToolTip(_translate("DlgAddEditEvent", "Add indication to patient\'s profile"))
        self.btnAddEvent.setText(_translate("DlgAddEditEvent", "-->"))
        self.btnRemoveEvent.setToolTip(_translate("DlgAddEditEvent", "Remove indication from patient\'s profile"))
        self.btnRemoveEvent.setText(_translate("DlgAddEditEvent", "<--"))
        self.lblComment.setText(_translate("DlgAddEditEvent", "Comment"))
        self.txtComment_event.setToolTip(_translate("DlgAddEditEvent", "Add clinically relevant comments"))
        self.txtComment_event.setPlaceholderText(_translate("DlgAddEditEvent", "Type any clinically relevant information pertaining to the result."))
        self.btnOK_event.setText(_translate("DlgAddEditEvent", "OK"))
        self.btnCancel_event.setText(_translate("DlgAddEditEvent", "Cancel"))
import gui.resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgAddEditEvent = QtWidgets.QDialog()
    ui = Ui_DlgAddEditEvent()
    ui.setupUi(DlgAddEditEvent)
    DlgAddEditEvent.show()
    sys.exit(app.exec_())
