# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editindication.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgEditIndication(object):
    def setupUi(self, DlgEditIndication):
        DlgEditIndication.setObjectName("DlgEditIndication")
        DlgEditIndication.resize(342, 71)
        self.widget = QtWidgets.QWidget(DlgEditIndication)
        self.widget.setGeometry(QtCore.QRect(10, 10, 321, 53))
        self.widget.setObjectName("widget")
        self.lytMain = QtWidgets.QVBoxLayout(self.widget)
        self.lytMain.setContentsMargins(0, 0, 0, 0)
        self.lytMain.setObjectName("lytMain")
        self.ledIndication = QtWidgets.QLineEdit(self.widget)
        self.ledIndication.setObjectName("ledIndication")
        self.lytMain.addWidget(self.ledIndication)
        self.lytButtons = QtWidgets.QHBoxLayout()
        self.lytButtons.setObjectName("lytButtons")
        self.btnOk = QtWidgets.QPushButton(self.widget)
        self.btnOk.setObjectName("btnOk")
        self.lytButtons.addWidget(self.btnOk)
        self.btnExit = QtWidgets.QPushButton(self.widget)
        self.btnExit.setObjectName("btnExit")
        self.lytButtons.addWidget(self.btnExit)
        self.lytMain.addLayout(self.lytButtons)

        self.retranslateUi(DlgEditIndication)
        QtCore.QMetaObject.connectSlotsByName(DlgEditIndication)

    def retranslateUi(self, DlgEditIndication):
        _translate = QtCore.QCoreApplication.translate
        DlgEditIndication.setWindowTitle(_translate("DlgEditIndication", "Edit Indication"))
        self.btnOk.setText(_translate("DlgEditIndication", "OK"))
        self.btnExit.setText(_translate("DlgEditIndication", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgEditIndication = QtWidgets.QDialog()
    ui = Ui_DlgEditIndication()
    ui.setupUi(DlgEditIndication)
    DlgEditIndication.show()
    sys.exit(app.exec_())
