# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messagebox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QDialog, QWidget

import sys
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *

class Ui_DlgMessageBoxCritical(QDialog):
    def setupUi(self, dlgMessageBoxCritical):
        dlgMessageBoxCritical.setObjectName("dlgMessageBoxCritical")
        dlgMessageBoxCritical.resize(494, 212)
        palette = QtGui.QPalette()
        dlgMessageBoxCritical.setPalette(palette)
        dlgMessageBoxCritical.setStyleSheet("QTextEdit {\n"
"    border: none;"                                           
"    background-color: white;\n"
"    padding: 3px;\n"
"    font-family:  \"Raleway\";\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLabel#lblColor {\n"
"    border: 3px solid #00b4d8;\n"
"    border-radius: 15px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #00b4d8;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    font-family: \"Readex Pro\";\n"
"    font: 12px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border: 3px solid #0077b6;\n"
"}\n"
"")
        self.tedMessage = QtWidgets.QTextEdit(dlgMessageBoxCritical)
        # self.tedMessage.setGeometry(QtCore.QRect(30, 10, 441, 141))
        self.tedMessage.setGeometry(QtCore.QRect(30, 10, 441, 61))
        self.tedMessage.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.tedMessage.setObjectName("tedMsg")
        self.tedMessage.setReadOnly(True)
        self.tedMessage.LineWrapMode(QTextEdit.WidgetWidth)
        self.tedMessage.setWordWrapMode(QTextOption.WrapAnywhere)
        self.btnOk = QtWidgets.QPushButton(dlgMessageBoxCritical)
        # self.btnOk.setGeometry(QtCore.QRect(430, 170, 51, 31))
        self.btnOk.setGeometry(QtCore.QRect(430, 80, 51, 25))
        self.btnOk.setObjectName("btnOk")
        self.btnOk.clicked.connect(self.close)
        self.lblColor = QtWidgets.QLabel(dlgMessageBoxCritical)
        # self.lblColor.setGeometry(QtCore.QRect(10, 0, 481, 211))
        self.lblColor.setGeometry(QtCore.QRect(10, 0, 481, 111))
        self.lblColor.setText("")
        self.lblColor.setObjectName("lblColor")
        self.lblColor.lower()
        self.tedMessage.raise_()
        self.btnOk.raise_()

        self.retranslateUi(dlgMessageBoxCritical)
        QtCore.QMetaObject.connectSlotsByName(dlgMessageBoxCritical)

    def retranslateUi(self, dlgMessageBoxCritical):
        _translate = QtCore.QCoreApplication.translate
        dlgMessageBoxCritical.setWindowTitle(_translate("DlgMessageBox", "Dialog"))
        self.tedMessage.setText(_translate("DlgMessageBox", "TextLabel"))
        self.btnOk.setText(_translate("DlgMessageBox", "Okay"))

import gui.resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgMessageBoxCritical = QtWidgets.QDialog()
    dlgMessageBoxCritical.setWindowFlag(Qt.FramelessWindowHint)
    dlgMessageBoxCritical.setAttribute(Qt.WA_TranslucentBackground)
    dlgMessageBoxCritical.setModal(True)
    ui = Ui_DlgMessageBoxCritical()
    ui.setupUi(dlgMessageBoxCritical)
    dlgMessageBoxCritical.show()
    sys.exit(app.exec_())
