# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'message_box_question.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QDialog


class Ui_DlgMessageBoxQuestion(QDialog):
    def setupUi(self, dlgMessageBoxQuestion):
        dlgMessageBoxQuestion.setObjectName("dlgMessageBox")
        dlgMessageBoxQuestion.resize(494, 212)
        palette = QtGui.QPalette()
        dlgMessageBoxQuestion.setPalette(palette)
        dlgMessageBoxQuestion.setStyleSheet("QLabel#lblMessage {\n"
"    background-color: white;\n"
"    padding: 20px;\n"
"    font-family:  \"Raleway\";\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLabel#lblColor {\n"
"    border: 3px solid #00b4d8;\n"
"    border-radius: 15px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #00b4d8;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    font-family: \"Readex Pro\";\n"
"    font: 12px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border: 3px solid #0077b6;\n"
"}\n"
"")
        self.lblMessage = QtWidgets.QLabel(dlgMessageBoxQuestion)
        self.lblMessage.setGeometry(QtCore.QRect(30, 10, 441, 141))
        self.lblMessage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblMessage.setObjectName("lblMessage")
        self.btnAccept = QtWidgets.QPushButton(dlgMessageBoxQuestion)
        self.btnAccept.setGeometry(QtCore.QRect(430, 170, 51, 31))
        self.btnAccept.setObjectName("btnAccept")
        self.lblColor = QtWidgets.QLabel(dlgMessageBoxQuestion)
        self.lblColor.setGeometry(QtCore.QRect(10, 0, 481, 211))
        self.lblColor.setText("")
        self.lblColor.setObjectName("lblColor")
        self.btnDecline = QtWidgets.QPushButton(dlgMessageBoxQuestion)
        self.btnDecline.setGeometry(QtCore.QRect(370, 170, 51, 31))
        self.btnDecline.setDefault(True)
        self.btnDecline.setObjectName("btnDecline")
        self.lblColor.raise_()
        self.lblMessage.raise_()
        self.btnAccept.raise_()
        self.btnDecline.raise_()

        self.retranslateUi(dlgMessageBoxQuestion)
        QtCore.QMetaObject.connectSlotsByName(dlgMessageBoxQuestion)

    def retranslateUi(self, DlgMessageBox):
        _translate = QtCore.QCoreApplication.translate
        DlgMessageBox.setWindowTitle(_translate("DlgMessageBox", "Dialog"))
        self.lblMessage.setText(_translate("DlgMessageBox", "TextLabel"))
        self.btnAccept.setText(_translate("DlgMessageBox", "Accept"))
        self.btnDecline.setText(_translate("DlgMessageBox", "Decline"))
import gui.resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgMessageBoxQuestion = QtWidgets.QDialog()
    dlgMessageBoxQuestion.setWindowFlag(Qt.FramelessWindowHint)
    dlgMessageBoxQuestion.setAttribute(Qt.WA_TranslucentBackground)
    dlgMessageBoxQuestion.setModal(True)
    ui = Ui_DlgMessageBoxQuestion()
    ui.setupUi(dlgMessageBoxQuestion)
    dlgMessageBoxQuestion.show()
    sys.exit(app.exec_())
