# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgReport(object):
    def setupUi(self, DlgReport):
        DlgReport.setObjectName("DlgReport")
        DlgReport.resize(435, 646)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 242, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 242, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 242, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 242, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        DlgReport.setPalette(palette)
        DlgReport.setStyleSheet("QPushButton {\n"
"    background-color: #00b4d8;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    font-family: \"Readex Pro\";\n"
"    font: 12px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border: 3px solid #0077b6;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px  solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-family:  \"Readex Pro\";\n"
"    font: 12px;\n"
"\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #5E60CE;\n"
"    font-family: \"Raleway\";\n"
"    font-size: 36px;    \n"
"    font-weight: bold;\n"
"    margin: 0;\n"
"}")
        self.widget = QtWidgets.QWidget(DlgReport)
        self.widget.setGeometry(QtCore.QRect(11, 11, 411, 621))
        self.widget.setObjectName("widget")
        self.lytMain = QtWidgets.QVBoxLayout(self.widget)
        self.lytMain.setContentsMargins(0, 0, 0, 0)
        self.lytMain.setObjectName("lytMain")
        self.lblHeader = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeader.setFont(font)
        self.lblHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeader.setObjectName("lblHeader")
        self.lytMain.addWidget(self.lblHeader)
        self.lytRbtn = QtWidgets.QHBoxLayout()
        self.lytRbtn.setObjectName("lytRbtn")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lytRbtn.addItem(spacerItem)
        self.rbtAll = QtWidgets.QRadioButton(self.widget)
        self.rbtAll.setObjectName("rbtAll")
        self.buttonGroup = QtWidgets.QButtonGroup(DlgReport)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rbtAll)
        self.lytRbtn.addWidget(self.rbtAll)
        self.rbtActive = QtWidgets.QRadioButton(self.widget)
        self.rbtActive.setChecked(True)
        self.rbtActive.setObjectName("rbtActive")
        self.buttonGroup.addButton(self.rbtActive)
        self.lytRbtn.addWidget(self.rbtActive)
        self.rbtInactive = QtWidgets.QRadioButton(self.widget)
        self.rbtInactive.setObjectName("rbtInactive")
        self.buttonGroup.addButton(self.rbtInactive)
        self.lytRbtn.addWidget(self.rbtInactive)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lytRbtn.addItem(spacerItem1)
        self.lytMain.addLayout(self.lytRbtn)
        self.tedReport = QtWidgets.QTextEdit(self.widget)
        self.tedReport.setReadOnly(True)
        self.tedReport.setObjectName("tedReport")
        self.lytMain.addWidget(self.tedReport)
        self.lytButtons = QtWidgets.QHBoxLayout()
        self.lytButtons.setObjectName("lytButtons")
        self.btnPatientList = QtWidgets.QPushButton(self.widget)
        self.btnPatientList.setMinimumSize(QtCore.QSize(0, 30))
        self.btnPatientList.setObjectName("btnPatientList")
        self.lytButtons.addWidget(self.btnPatientList)
        self.btnPDF = QtWidgets.QPushButton(self.widget)
        self.btnPDF.setMinimumSize(QtCore.QSize(0, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPDF.setIcon(icon)
        self.btnPDF.setObjectName("btnPDF")
        self.lytButtons.addWidget(self.btnPDF)
        self.btnExit = QtWidgets.QPushButton(self.widget)
        self.btnExit.setMinimumSize(QtCore.QSize(0, 30))
        self.btnExit.setObjectName("btnExit")
        self.lytButtons.addWidget(self.btnExit)
        self.lytMain.addLayout(self.lytButtons)

        self.retranslateUi(DlgReport)
        QtCore.QMetaObject.connectSlotsByName(DlgReport)

    def retranslateUi(self, DlgReport):
        _translate = QtCore.QCoreApplication.translate
        DlgReport.setWindowTitle(_translate("DlgReport", "Clinic Report"))
        self.lblHeader.setText(_translate("DlgReport", "Clinic Report"))
        self.rbtAll.setText(_translate("DlgReport", "All"))
        self.rbtActive.setText(_translate("DlgReport", "Active"))
        self.rbtInactive.setText(_translate("DlgReport", "Inactive"))
        self.btnPatientList.setText(_translate("DlgReport", "Patient List"))
        self.btnPDF.setText(_translate("DlgReport", "Export to PDF"))
        self.btnExit.setText(_translate("DlgReport", "Exit"))
import gui.resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgReport = QtWidgets.QDialog()
    ui = Ui_DlgReport()
    ui.setupUi(DlgReport)
    DlgReport.show()
    sys.exit(app.exec_())
