# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgReport(object):
    def setupUi(self, DlgReport):
        DlgReport.setObjectName("DlgReport")
        DlgReport.resize(436, 582)
        self.widget = QtWidgets.QWidget(DlgReport)
        self.widget.setGeometry(QtCore.QRect(10, 10, 411, 561))
        self.widget.setObjectName("widget")
        self.lytMain = QtWidgets.QVBoxLayout(self.widget)
        self.lytMain.setContentsMargins(0, 0, 0, 0)
        self.lytMain.setObjectName("lytMain")
        self.lblHeader = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeader.setFont(font)
        self.lblHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeader.setObjectName("lblHeader")
        self.lytMain.addWidget(self.lblHeader)
        self.tedReport = QtWidgets.QTextEdit(self.widget)
        self.tedReport.setReadOnly(True)
        self.tedReport.setObjectName("tedReport")
        self.lytMain.addWidget(self.tedReport)
        self.lytButtons = QtWidgets.QHBoxLayout()
        self.lytButtons.setObjectName("lytButtons")
        self.btnPDF = QtWidgets.QPushButton(self.widget)
        self.btnPDF.setObjectName("btnPDF")
        self.lytButtons.addWidget(self.btnPDF)
        self.btnExit = QtWidgets.QPushButton(self.widget)
        self.btnExit.setObjectName("btnExit")
        self.lytButtons.addWidget(self.btnExit)
        self.lytMain.addLayout(self.lytButtons)

        self.retranslateUi(DlgReport)
        QtCore.QMetaObject.connectSlotsByName(DlgReport)

    def retranslateUi(self, DlgReport):
        _translate = QtCore.QCoreApplication.translate
        DlgReport.setWindowTitle(_translate("DlgReport", "Clinic Report"))
        self.lblHeader.setText(_translate("DlgReport", "Clinic Report"))
        self.btnPDF.setText(_translate("DlgReport", "Export to PDF"))
        self.btnExit.setText(_translate("DlgReport", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DlgReport = QtWidgets.QDialog()
    ui = Ui_DlgReport()
    ui.setupUi(DlgReport)
    DlgReport.show()
    sys.exit(app.exec_())
